export type GaleriaPhoto = {
  src: string;
  alt: string;
  label: string;
  location?: string;
};

// Aby dodać nowe zdjęcia:
// 1. Wrzuć plik do /public/galeria-okolicy/
// 2. Dopisz wpis do tej tablicy

export const galeriaOkolicy: GaleriaPhoto[] = [
  {
    src: "/galeria-okolicy/wola-uhruska-panorama.jpg",
    alt: "Panorama Woli Uhruskiej z lotu ptaka",
    label: "Wola Uhruska z drona",
    location: "Wola Uhruska",
  },
  {
    src: "/galeria-okolicy/bug-meandry-z-drona.jpg",
    alt: "Meandry rzeki Bug z lotu ptaka",
    label: "Meandry Bugu",
    location: "Dolina Bugu",
  },
  {
    src: "/galeria-okolicy/kapielisko-pompka-plaza.jpg",
    alt: "Kąpielisko Pompka — plaża i wypożyczalnia kajaków",
    label: "Kąpielisko Pompka",
    location: "Wola Uhruska",
  },
  {
    src: "/galeria-okolicy/wieza-widokowa.jpg",
    alt: "Wieża widokowa w Woli Uhruskiej",
    label: "Wieża widokowa",
    location: "Wola Uhruska",
  },
  {
    src: "/galeria-okolicy/dab-bolko-hniszow.jpg",
    alt: "Dąb Bolko w Hniszowie z lotu ptaka",
    label: "Dąb Bolko",
    location: "Hniszów",
  },
  {
    src: "/galeria-okolicy/grzybobranie-borowik.jpg",
    alt: "Borowik zebrany w okolicznych lasach",
    label: "Grzybobranie — borowik",
    location: "Lasy Poleskie",
  },
  {
    src: "/galeria-okolicy/zachod-slonca-jezioro.jpg",
    alt: "Zachod slonca nad jeziorem",
    label: "Zachod slonca",
    location: "Okolice Woli Uhruskiej",
  },
  {
    src: "/galeria-okolicy/staw-pomost-lodka.jpg",
    alt: "Staw z pomostem i lodka",
    label: "Staw z pomostem",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/karpie-koi-staw.jpg",
    alt: "Karpie koi plywajace w stawie wsrod lilii wodnych",
    label: "Karpie koi",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/staw-zima-snieg.jpg",
    alt: "Staw zimą otoczony ośnieżonymi drzewami",
    label: "Staw zimą",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/jacuzzi-noc.jpg",
    alt: "Jacuzzi z fioletowym podswietleniem noca",
    label: "Jacuzzi nocą",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/ogrod-noc-lampki.jpg",
    alt: "Drzewo ozdobione lampkami nocą",
    label: "Ogrod nocą",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/hustawka-noc.jpg",
    alt: "Drewniana huśtawka nocą z kolorowymi lampkami",
    label: "Huśtawka nocą",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/agrest-krzew.jpg",
    alt: "Krzew agrestu z dojrzalymi owocami",
    label: "Agrest",
    location: "Sad owocowy",
  },
  {
    src: "/galeria-okolicy/maliny-krzew.jpg",
    alt: "Dojrzale maliny na krzewie",
    label: "Maliny",
    location: "Sad owocowy",
  },
  {
    src: "/galeria-okolicy/morwa-drzewo.jpg",
    alt: "Drzewo morwy z dojrzalymi czarnymi owocami",
    label: "Morwa",
    location: "Sad owocowy",
  },
  {
    src: "/galeria-okolicy/czeresnie-drzewo.jpg",
    alt: "Czereśnie na drzewie",
    label: "Czereśnie",
    location: "Sad owocowy",
  },
  {
    src: "/galeria-okolicy/borowki-krzew.jpg",
    alt: "Borówki amerykańskie na krzewie",
    label: "Borowki",
    location: "Sad owocowy",
  },
  {
    src: "/galeria-okolicy/poziomki-lesne.jpg",
    alt: "Dzikie poziomki rosnace w trawie",
    label: "Poziomki leśne",
    location: "Okolice",
  },
  {
    src: "/galeria-okolicy/szczupak-zimowy.jpg",
    alt: "Zlowiony szczupak na śniegu z wedka",
    label: "Szczupak — zimowy polow",
    location: "Wedkarstwo",
  },
  {
    src: "/galeria-okolicy/szczupak-duzy.jpg",
    alt: "Duzy szczupak zlowiony wedką",
    label: "Szczupak",
    location: "Wedkarstwo",
  },
  {
    src: "/galeria-okolicy/karp-podbierak.jpg",
    alt: "Karp w podbieraku na trawie",
    label: "Karp",
    location: "Wedkarstwo",
  },
  {
    src: "/galeria-okolicy/karp-zlowiony.jpg",
    alt: "Zlowiony karp na trawie",
    label: "Karp",
    location: "Wedkarstwo",
  },
  {
    src: "/galeria-okolicy/sandacz-zlowiony.jpg",
    alt: "Sandacz zlowiony w reku nad stawem",
    label: "Sandacz",
    location: "Wedkarstwo",
  },
  {
    src: "/galeria-okolicy/czubajka-grzyb.jpg",
    alt: "Czubajka kania rosnaca w trawie",
    label: "Czubajka kania",
    location: "Grzybobranie",
  },
  {
    src: "/galeria-okolicy/grzyby-podgrzybki.jpg",
    alt: "Podgrzybki w trawie",
    label: "Podgrzybki",
    location: "Grzybobranie",
  },
  {
    src: "/galeria-okolicy/czubajki-las.jpg",
    alt: "Czubajki kanie zebrane w lesie",
    label: "Czubajki kanie",
    location: "Grzybobranie",
  },
  {
    src: "/galeria-okolicy/domek-noc-staw.jpg",
    alt: "Domek nocą widoczny ze stawu z girlandami swiatelnymi",
    label: "Domek nocą",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-staw-mostek.jpg",
    alt: "Domek widziany ze stawu przez drewniany mostek",
    label: "Domek od strony stawu",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/staw-swit-mgla.jpg",
    alt: "Staw o swicie we mgle z wedka",
    label: "Staw o swicie",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/staw-mgla-rano.jpg",
    alt: "Staw we mgle wczesnym rankiem",
    label: "Staw o poranku",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/glicynia-kwiaty.jpg",
    alt: "Glicynia z fioletowymi kwiatami",
    label: "Glicynia",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/sosna-ogrod.jpg",
    alt: "Mloda sosna w ogrodzie z domkiem w tle",
    label: "Ogrod",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/tecza-nad-polem.jpg",
    alt: "Tecza nad polami w okolicach Woli Uhruskiej",
    label: "Tecza",
    location: "Okolice Woli Uhruskiej",
  },
  {
    src: "/galeria-okolicy/rowery-ogrod.jpg",
    alt: "Dwa rowery w ogrodzie dostepne dla gosci",
    label: "Rowery",
    location: "Nadbuzanski Zakatek",
  },
  // Lotnicze / dron
  {
    src: "/galeria-okolicy/wola-uhruska-dron-wies.jpg",
    alt: "Wola Uhruska z lotu ptaka — kosciol i rzeka Bug jesienia",
    label: "Wola Uhruska jesienia",
    location: "Wola Uhruska",
  },
  {
    src: "/galeria-okolicy/bug-dolina-panorama.jpg",
    alt: "Dolina Bugu — rozlegla panorama z drona latem",
    label: "Dolina Bugu — panorama",
    location: "Dolina Bugu",
  },
  {
    src: "/galeria-okolicy/bug-dolina-dron-meandry.jpg",
    alt: "Meandry rzeki Bug z drona jesienia",
    label: "Meandry Bugu jesienia",
    location: "Dolina Bugu",
  },
  {
    src: "/galeria-okolicy/bug-dolina-pola-dron.jpg",
    alt: "Dolina Bugu i okoliczne pola z drona",
    label: "Bug i pola z drona",
    location: "Dolina Bugu",
  },
  {
    src: "/galeria-okolicy/posesja-z-drona.jpg",
    alt: "Posesja Nadbuzanskiego Zakatka z drona — domek wśrod lasow",
    label: "Posesja z drona",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/posesja-stawy-dron.jpg",
    alt: "Posesja ze stawami z lotu ptaka",
    label: "Stawy z drona",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/posesja-okolica-dron.jpg",
    alt: "Posesja z wioska w tle — widok z drona",
    label: "Posesja i okolica z drona",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/labedzie-mokradla-dron.jpg",
    alt: "Labedzie na mokradlach Polesia z drona",
    label: "Labedzie na mokradlach",
    location: "Polesie Lubelskie",
  },
  {
    src: "/galeria-okolicy/poleski-mokradla-dron.jpg",
    alt: "Mokradla Poleskie z drona z promieniami slonca",
    label: "Mokradla Poleskie",
    location: "Polesie Lubelskie",
  },
  {
    src: "/galeria-okolicy/kombajn-zniwa.jpg",
    alt: "Kombajn zbozowy podczas zniw — widok z drona",
    label: "Zniwa z drona",
    location: "Okolice Woli Uhruskiej",
  },
  {
    src: "/galeria-okolicy/kombajn-z-gory.jpg",
    alt: "Kombajn z lotu ptaka zbierajacy zboza",
    label: "Kombajn z gory",
    location: "Okolice Woli Uhruskiej",
  },
  // Ogrod i kwiaty
  {
    src: "/galeria-okolicy/magnolia-ogrod.jpg",
    alt: "Magnolia z rozowoymi kwiatami w ogrodzie wiosna",
    label: "Magnolia",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/roza-pstrokata.jpg",
    alt: "Pstrokata roza czerwono-biala w ogrodzie",
    label: "Roza ogrodowa",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/dzwonki-polne.jpg",
    alt: "Dzwonki polne fioletowe trzymane w rece",
    label: "Dzwonki polne",
    location: "Okolice",
  },
  {
    src: "/galeria-okolicy/irysy-ogrod.jpg",
    alt: "Niebieskie irysy kwitnace w ogrodzie",
    label: "Irysy",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/porzeczka-czerwona.jpg",
    alt: "Krzew porzeczki czerwonej z owocami",
    label: "Porzeczka czerwona",
    location: "Sad owocowy",
  },
  {
    src: "/galeria-okolicy/bukiet-kwiatow.jpg",
    alt: "Bukiet z hortensji i polnych kwiatow",
    label: "Bukiet z ogrodu",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/maki-pole.jpg",
    alt: "Czerwone maki na polu",
    label: "Maki polne",
    location: "Okolice Woli Uhruskiej",
  },
  {
    src: "/galeria-okolicy/facelia-pole.jpg",
    alt: "Pole faceliia w fioletowych kwiatach pod niebieskim niebem",
    label: "Pole faceli",
    location: "Okolice Woli Uhruskiej",
  },
  {
    src: "/galeria-okolicy/kallistemon-ogrod.jpg",
    alt: "Kallistemon z czerwonymi kwiatami w ogrodzie",
    label: "Kallistemon",
    location: "Nadbuzanski Zakatek",
  },
  // Woda, stawy, przyroda
  {
    src: "/galeria-okolicy/labedzie-rzeka.jpg",
    alt: "Cztery labedzie plywajace na rzece",
    label: "Labedzie",
    location: "Dolina Bugu",
  },
  {
    src: "/galeria-okolicy/narybek-koi.jpg",
    alt: "Mlode karpie koi w kuwecie",
    label: "Narybek koi",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/karpie-koi-transport.jpg",
    alt: "Kolorowe karpie koi w torbie transportowej",
    label: "Karpie koi",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/ryba-w-stawie-lilie.jpg",
    alt: "Duza ryba plywajaca w stawie wsrod lilii wodnych",
    label: "Ryba w stawie",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/lilia-wodna-staw.jpg",
    alt: "Rozowa lilia wodna kwitnaca w stawie",
    label: "Lilia wodna",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/lilia-wodna-rozowa.jpg",
    alt: "Rozowa lilia wodna z bliska na ciemnej wodzie",
    label: "Lilia wodna — zbliżenie",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/trzciny-palki.jpg",
    alt: "Trzciny i palki wodne przy brzegu stawu",
    label: "Trzciny przy stawie",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/tecza-nad-stawem.jpg",
    alt: "Tecza odbijajaca sie w stawie z liliami wodnymi",
    label: "Tecza nad stawem",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/wedkowanie-z-pomostu.jpg",
    alt: "Wedkowanie z drewnianego pomostu nad stawem",
    label: "Wedkowanie z pomostu",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/wedkowanie-noca.jpg",
    alt: "Nocne wedkowanie przy stawie ze swietlistym splawem",
    label: "Wedkowanie noca",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/karp-w-siatce.jpg",
    alt: "Zlowiony karp w podbieraku na trawie",
    label: "Karp z polowu",
    location: "Wedkarstwo",
  },
  {
    src: "/galeria-okolicy/jezioro-pomost-zachod.jpg",
    alt: "Jezioro o zachodzie slonca — dlug pomost i spokojna woda",
    label: "Jezioro o zachodzie",
    location: "Okolice",
  },
  {
    src: "/galeria-okolicy/lodka-rc-staw.jpg",
    alt: "Modelowa lodka RC plywajaca po stawie",
    label: "Lodka RC na stawie",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-od-stawu-lato.jpg",
    alt: "Domek widoczny zza stawu z liliami wodnymi latem",
    label: "Domek od strony stawu",
    location: "Nadbuzanski Zakatek",
  },
  // Zima
  {
    src: "/galeria-okolicy/domek-zima.jpg",
    alt: "Drewniany domek pokryty sniegiem zima",
    label: "Domek zima",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-zima-staw-lod.jpg",
    alt: "Domek zimą nad zamarzniętym stawem",
    label: "Domek nad lodem",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-zima-mostek-lod.jpg",
    alt: "Domek zimą z mostem nad zamarzniętym stawem",
    label: "Domek i mostek zima",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/ogrod-zima-slonce.jpg",
    alt: "Zasniezone swierkowy ogrod w sloneczny zimowy dzien",
    label: "Ogrod zima",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/ogrod-zima-lawka.jpg",
    alt: "Ogrod zimowy ze sniegiem i lawka z okraglakow",
    label: "Ogrod — zimowa lawka",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/ogrod-zima-swierk.jpg",
    alt: "Wysokie swierk pokryte sniegiem w zimowym ogrodzie",
    label: "Swierk zimą",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/swierk-snieg-detal.jpg",
    alt: "Maly swierek z czapa sniegu — detal zimowy",
    label: "Zimowy detal",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/pies-jagody-zima.jpg",
    alt: "Pies spacerujacy po sniegu z jagodami glogu na galazce",
    label: "Zima w ogrodzie",
    location: "Nadbuzanski Zakatek",
  },
  // Zachody slonca i noc
  {
    src: "/galeria-okolicy/domek-noc-odbicie.jpg",
    alt: "Domek nocą odbijajacy sie w wodzie wsrod swierkow",
    label: "Domek nocą — odbicie",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-noc-girlandy.jpg",
    alt: "Domek nocą z girlandami swietlnymi odbijajacymi sie w stawie",
    label: "Domek z girlandami",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-noc-staw-panorama.jpg",
    alt: "Domek i swiatla nocne odbite w szerokim stawie",
    label: "Domek nocą — panorama",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-taras-noc.jpg",
    alt: "Domek i taras oswietlone nocą",
    label: "Taras nocą",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/taras-wieczor-gosc.jpg",
    alt: "Goscie na tarasie domku o wieczorze",
    label: "Wieczor na tarasie",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/hustawka-jbl-noc.jpg",
    alt: "Hustawka ogrodowa nocą z glosnikiem JBL i neonowym napisem",
    label: "Hustawka nocą",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/zachod-brzozy.jpg",
    alt: "Zachod slonca przez sylwety brzoz",
    label: "Zachod przez brzozy",
    location: "Okolice",
  },
  {
    src: "/galeria-okolicy/zachod-kukurydza.jpg",
    alt: "Dramatyczny pomaranczowy zachod slonca wsrod kukurydzy",
    label: "Zachod w kukurydzy",
    location: "Okolice",
  },
  {
    src: "/galeria-okolicy/ksiezyc-mgla-pola.jpg",
    alt: "Wschod ksiezyca nad zamglonymi polami o swicie",
    label: "Ksiezyc nad polami",
    location: "Okolice",
  },
  // Grzybobranie
  {
    src: "/galeria-okolicy/borowik-liscie-las.jpg",
    alt: "Borowik szlachetny rosnacy wsrod jesiennych lisci w lesie",
    label: "Borowik jesienią",
    location: "Grzybobranie",
  },
  {
    src: "/galeria-okolicy/kozlarz-debowy.jpg",
    alt: "Kozlarz debowy z pomaranczowym kapeluszem wsrod debowych zoledi",
    label: "Kozlarz debowy",
    location: "Grzybobranie",
  },
  {
    src: "/galeria-okolicy/dwa-borowiki.jpg",
    alt: "Dwa borowiki rosnace blisko siebie w lesie",
    label: "Dwa borowiki",
    location: "Grzybobranie",
  },
  {
    src: "/galeria-okolicy/borowik-ogromny.jpg",
    alt: "Ogromny borowik trzymany w rece — okaz ze zbiorow",
    label: "Borowik — okaz",
    location: "Grzybobranie",
  },
  {
    src: "/galeria-okolicy/borowiki-w-dloni.jpg",
    alt: "Dwa borowiki trzymane w dloni w lesie",
    label: "Borowiki w dloni",
    location: "Grzybobranie",
  },
  {
    src: "/galeria-okolicy/kosz-grzybow.jpg",
    alt: "Pelny kosz grzybow zebranych w okolicznych lasach",
    label: "Kosz grzybow",
    location: "Grzybobranie",
  },
  {
    src: "/galeria-okolicy/borowik-bokeh.jpg",
    alt: "Borowik w jesiennym lesie — artystyczne zdjecie bokeh",
    label: "Borowik — bokeh",
    location: "Grzybobranie",
  },
  {
    src: "/galeria-okolicy/duzy-grzyb-reka.jpg",
    alt: "Duzy grzyb trzymany w rece w slonecznym lesie",
    label: "Duzy grzyb",
    location: "Grzybobranie",
  },
  // Las i krajobraz
  {
    src: "/galeria-okolicy/las-sosnowy-promienie.jpg",
    alt: "Las sosnowy z promieniami slonca przebijajacymi przez korony drzew",
    label: "Las sosnowy",
    location: "Lasy Poleskie",
  },
  {
    src: "/galeria-okolicy/las-sosnowy-jesien.jpg",
    alt: "Sosny jesienią — zlote liscie i wysokie pnie",
    label: "Las jesienia",
    location: "Lasy Poleskie",
  },
  {
    src: "/galeria-okolicy/wieza-drzewo-sylwetka.jpg",
    alt: "Silhoueta duzego drzewa z wieza widokowa w tle o zmierzchu",
    label: "Drzewo i wieza widokowa",
    location: "Wola Uhruska",
  },
  // Motocykle i aktywnosc
  {
    src: "/galeria-okolicy/motor-maki-pole.jpg",
    alt: "Motocykl Aprilia na tle pola czerwonych makow",
    label: "Maki i motor",
    location: "Okolice",
  },
  {
    src: "/galeria-okolicy/motor-rzepak-pole.jpg",
    alt: "Motocykl na tle zoltego pola rzepaku",
    label: "Rzepak i motor",
    location: "Okolice",
  },
  {
    src: "/galeria-okolicy/motor-ktm-pole.jpg",
    alt: "Motocykl terenowy KTM na polu",
    label: "Motor w terenie",
    location: "Okolice",
  },
  {
    src: "/galeria-okolicy/motor-ktm-zachod.jpg",
    alt: "Motor KTM i zachod slonca nad lacami",
    label: "Motor i zachod slonca",
    location: "Okolice",
  },
  {
    src: "/galeria-okolicy/motor-rzepak-chmury.jpg",
    alt: "Motocykl KTM na tle rzepaku i bialych chmur",
    label: "Motor i rzepak",
    location: "Okolice",
  },
  {
    src: "/galeria-okolicy/dziewczyna-pole-zachod.jpg",
    alt: "Sylweta na polu lacki przy zachodzie slonca",
    label: "Zachod na lace",
    location: "Okolice",
  },
  // Zycie na posesji
  {
    src: "/galeria-okolicy/grill-biesiada.jpg",
    alt: "Grillowane miesa i kielbasy — biesiada na tarasie",
    label: "Grillowanie",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/wedzarnia-produkty.jpg",
    alt: "Wedzarnia z wedzonym miesem i rybami",
    label: "Wedzarnia",
    location: "Nadbuzanski Zakatek",
  },
  // Dron sierpien 2026 — dzien
  {
    src: "/galeria-okolicy/domek-dron-taras-ogrod.jpg",
    alt: "Domek z drona — taras z parasolem i ogrod latem",
    label: "Domek z drona",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/stawy-dron-sierpien.jpg",
    alt: "Stawy rybne z drona — trzy zbiorniki wsrod drzew",
    label: "Stawy z drona",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/posesja-dron-staw-lato.jpg",
    alt: "Posesja z drona — domek, staw z liliami i basen latem",
    label: "Posesja latem",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/posesja-dron-stawy-lato2.jpg",
    alt: "Posesja z drona — domek wsrod staw i zielenią",
    label: "Domek i stawy",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/posesja-dron-pola-lato.jpg",
    alt: "Posesja z drona — szeroki widok na stawy, domek i pola",
    label: "Panorama z drona",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-dron-taras-lato.jpg",
    alt: "Domek z drona — taras z parasolem i stol do jedzenia",
    label: "Taras latem",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-dron-ogrod-lato.jpg",
    alt: "Domek z drona — ogrod z hustawka i staw przy sloncu",
    label: "Ogrod latem",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-dron-staw-lato.jpg",
    alt: "Domek z drona — staw z liliami i ogrod latem",
    label: "Staw i ogrod",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/ogrod-dron-atrakcje.jpg",
    alt: "Ogrod z drona — hustawka, leżaki, kajaki i boisko",
    label: "Atrakcje ogrodu",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/posesja-stawy-dron-lato.jpg",
    alt: "Posesja z drona — stawy i pola latem w sloncu",
    label: "Stawy i pola",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/wyspa-basen-dron.jpg",
    alt: "Mala wyspa ze stawu z basenem ogrodowym z drona",
    label: "Wyspa z basenem",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/posesja-dron-sierpien-pola.jpg",
    alt: "Posesja z drona — stawy i okolica sierpien",
    label: "Posesja sierpien",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-taras-sloneczny-lato.jpg",
    alt: "Domek od strony tarasu w sloneczny letni dzien",
    label: "Domek w sloncu",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-trzciny-lato.jpg",
    alt: "Domek widziany przez trzciny i ros­linnosc latem",
    label: "Domek przez trzciny",
    location: "Nadbuzanski Zakatek",
  },
  // Dron sierpien 2026 — noc
  {
    src: "/galeria-okolicy/domek-dron-noc-staw-zielony.jpg",
    alt: "Domek noca z drona — girlandy i zielone oswietlenie jacuzzi",
    label: "Domek noca z drona",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-dron-noc-bliski.jpg",
    alt: "Domek noca z drona — bliskie ujecie z girlandami",
    label: "Nocne girlandy",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-dron-noc-szeroki.jpg",
    alt: "Domek noca z drona — szeroki widok, swiatla miasta w tle",
    label: "Noc nad okolicą",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-dron-noc-girlandy2.jpg",
    alt: "Domek noca z drona — swiecace girlandy wzdluz ogrodu",
    label: "Girlandy z drona",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-taras-noc-blisko.jpg",
    alt: "Taras domku noca — osoba przy stole, ciepłe oswietlenie",
    label: "Taras noca",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-zmierzch-girlandy.jpg",
    alt: "Domek o zmierzchu z zapalonymi girlandami",
    label: "Zmierzch nad domkiem",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-gwiazdy-noc.jpg",
    alt: "Domek noca pod rozgwiezdzonym niebem",
    label: "Gwiazdy nad domkiem",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/domek-taras-gwiazdy-goscie.jpg",
    alt: "Goscie na tarasie domku pod rozgwiezdzonym niebem",
    label: "Wieczor pod gwiazdami",
    location: "Nadbuzanski Zakatek",
  },
  {
    src: "/galeria-okolicy/droga-mleczna-sierpien.jpg",
    alt: "Droga Mleczna nad Nadbuzanskim Zakatkiem — sierpien",
    label: "Droga Mleczna",
    location: "Nadbuzanski Zakatek",
  },
];
